const users = [
  {
    name: "Ngoako",
    email: "ngoakor12@gmail.com",
    messages: [
      {
        messageId: 1,
        recepientName: "Sarah",
        contactMethod: "email",
        email: "giftedesignco@gmail.com",
        subject: "Happy birthday Mom",
        content:
          "Happy birthday Mom! I hope you have a great day, stay blessed.",
        date: "13-01-2023",
        time: "09:00",
        state: "notSent",
        senderName: "Ngoako",
      },
      {
        messageId: 2,
        recepientName: "Mpho",
        contactMethod: "email",
        email: "giftedesignco@gmail.com",
        subject: "Happy birthday Mpho",
        content:
          "Happy birthday Mpho! I hope you have a great day, stay blessed.",
        date: "13-01-2023",
        time: "09:00",
        state: "notSent",
        senderName: "Ngoako",
      },
      {
        messageId: 3,
        recepientName: "Sebitso",
        contactMethod: "email",
        email: "giftedesignco@gmail.com",
        subject: "Happy birthday Sebitso",
        content:
          "Happy birthday Sebitso! I hope you have a great day, stay blessed.",
        date: "13-01-2023",
        time: "09:00",
        state: "notSent",
        senderName: "Ngoako",
      },
      {
        messageId: 5,
        recepientName: "Sarah",
        contactMethod: "email",
        email: "giftedesignco@gmail.com",
        subject: "Happy birthday Mom",
        content:
          "Happy birthday Mom! I hope you have a great day, stay blessed.",
        date: "13-01-2023",
        time: "09:00",
        state: "notSent",
        senderName: "Ngoako",
      },
      {
        messageId: 6,
        recepientName: "Mpho",
        contactMethod: "email",
        email: "giftedesignco@gmail.com",
        subject: "Happy birthday Mpho",
        content:
          "Happy birthday Mpho! I hope you have a great day, stay blessed.",
        date: "13-01-2023",
        time: "09:00",
        state: "notSent",
        senderName: "Ngoako",
      },
      {
        messageId: 7,
        recepientName: "Sebitso",
        contactMethod: "email",
        email: "giftedesignco@gmail.com",
        subject: "Happy birthday Sebitso",
        content:
          "Happy birthday Sebitso! I hope you have a great day, stay blessed.",
        date: "13-01-2023",
        time: "09:00",
        state: "notSent",
        senderName: "Ngoako",
      },
      {
        messageId: 8,
        recepientName: "Sarah",
        contactMethod: "email",
        email: "giftedesignco@gmail.com",
        subject: "Happy birthday Mom",
        content:
          "Happy birthday Mom! I hope you have a great day, stay blessed.",
        date: "13-01-2023",
        time: "09:00",
        state: "notSent",
        senderName: "Ngoako",
      },
      {
        messageId: 9,
        recepientName: "Mpho",
        contactMethod: "email",
        email: "giftedesignco@gmail.com",
        subject: "Happy birthday Mpho",
        content:
          "Happy birthday Mpho! I hope you have a great day, stay blessed.",
        date: "13-01-2023",
        time: "09:00",
        state: "notSent",
        senderName: "Ngoako",
      },
      {
        messageId: 10,
        recepientName: "Sebitso",
        contactMethod: "email",
        email: "giftedesignco@gmail.com",
        subject: "Happy birthday Sebitso",
        content:
          "Happy birthday Sebitso! I hope you have a great day, stay blessed.",
        date: "13-01-2023",
        time: "09:00",
        state: "notSent",
        senderName: "Ngoako",
      },
      {
        messageId: 11,
        recepientName: "Sarah",
        contactMethod: "email",
        email: "giftedesignco@gmail.com",
        subject: "Happy birthday Mom",
        content:
          "Happy birthday Mom! I hope you have a great day, stay blessed.",
        date: "13-01-2023",
        time: "09:00",
        state: "notSent",
        senderName: "Ngoako",
      },
      {
        messageId: 12,
        recepientName: "Mpho",
        contactMethod: "email",
        email: "giftedesignco@gmail.com",
        subject: "Happy birthday Mpho",
        content:
          "Happy birthday Mpho! I hope you have a great day, stay blessed.",
        date: "13-01-2023",
        time: "09:00",
        state: "notSent",
        senderName: "Ngoako",
      },
      {
        messageId: 13,
        recepientName: "Sebitso",
        contactMethod: "email",
        email: "giftedesignco@gmail.com",
        subject: "Happy birthday Sebitso",
        content:
          "Happy birthday Sebitso! I hope you have a great day, stay blessed.",
        date: "13-01-2023",
        time: "09:00",
        state: "notSent",
        senderName: "Ngoako",
      },
    ],
  },
  {
    name: "Ngoako2",
    email: "ngoakor12@gmail.com",
    messages: [
      {
        messageId: 14,
        recepientName: "Sebitso2",
        contactMethod: "email",
        email: "giftedesignco@gmail.com",
        subject: "Happy birthday Sebitso2",
        content:
          "Happy birthday Sebitso! I hope you have a great day, stay blessed2.",
        date: "13-01-2023",
        time: "09:00",
        state: "notSent",
        senderName: "Ngoako2",
      },
      {
        messageId: 15,
        recepientName: "Sebitso",
        contactMethod: "email",
        email: "giftedesignco@gmail.com",
        subject: "Happy birthday Sebitso",
        content:
          "Happy birthday Sebitso! I hope you have a great day, stay blessed.",
        date: "13-01-2023",
        time: "09:00",
        state: "notSent",
        senderName: "Ngoako",
      },
      {
        messageId: 16,
        recepientName: "Sebitso",
        contactMethod: "email",
        email: "giftedesignco@gmail.com",
        subject: "Happy birthday Sebitso",
        content:
          "Happy birthday Sebitso! I hope you have a great day, stay blessed.",
        date: "13-01-2023",
        time: "09:00",
        state: "notSent",
        senderName: "Ngoako",
      },
    ],
  },
];

export default users;
